pub const Code = enum(u8) { ERR_INVALID_ARGUMENT, ERR_NOT_FOUND, ERR_UNVERIFIED, ERR_IDENTITY_CHANGED, ERR_REVOKED, ERR_BLOCKED, ERR_BAD_CERTIFICATE, ERR_BAD_SIGNATURE, ERR_BAD_TRANSCRIPT, ERR_MODE_DOWNGRADE, ERR_UNSUPPORTED_CLASS, ERR_BAD_ENVELOPE, ERR_REPLAY, ERR_SKIPPED_KEY_LIMIT, ERR_RATE_LIMIT, ERR_CORE_UNAVAILABLE, ERR_STATE_CORRUPT, ERR_CRYPTO_FAILURE, ERR_REJECTED };
pub fn text(code: Code) []const u8 {
    return @tagName(code);
}
