pub const Code = enum(u8) {
    ERR_INVALID_ARGUMENT,
    ERR_NOT_FOUND,
    ERR_LOCKED,
    ERR_UNVERIFIED_PEER,
    ERR_CHANGED_IDENTITY,
    ERR_REVOKED_PEER,
    ERR_BLOCKED_PEER,
    ERR_MODE_DOWNGRADE,
    ERR_BAD_FRAME,
    ERR_BAD_ENVELOPE,
    ERR_BAD_CERTIFICATE,
    ERR_SESSION_CLOSED,
    ERR_STORAGE,
    ERR_NETWORK,
    ERR_RATE_LIMITED,
    ERR_BAD_SIGNATURE,
    ERR_BAD_TRANSCRIPT,
    ERR_UNSUPPORTED_CLASS,
    ERR_REPLAY,
    ERR_SKIPPED_KEY_LIMIT,
    ERR_CORE_UNAVAILABLE,
    ERR_STATE_CORRUPT,
    ERR_CRYPTO_FAILURE,
    ERR_REJECTED,
};
pub fn text(code: Code) []const u8 {
    return @tagName(code);
}
